### ISSUE TITLE
Rotation in the inertial frame 

### ISSUE THREAD

**Issue by rohitsupekar** [rohitsupekar/active_matter_spheres#2]
@kburns I was trying to implement the constant rigid rotation as an initial condition in the inertial frame. I am doing this by setting v_phi = Omega sin(theta) and then doing the forward transforms to get the coefficients following which I add random noise to the coefficients as before. This seems to work in serial but not in parallel... any ideas why and how to fix it? 

https://github.com/rohitsupekar/active_matter_spheres/blob/8fabb4dd1cbec2c18df9713707c602800a86fc0f/scripts/runningSimulation_pars_alan.py#L89-L106

**Comment by rohitsupekar** [comment]
@kburns Hi Keaton, just a gentle reminder about this. This is probably something trivial that I am missing.. There is no compact representation of sin(theta) in the (ell, m) space, which is why I need to set the field in real space and then transform back to the (ell, m) space [lines 92-94].

**Comment by kburns** [comment]
Hi Rohit, thanks for the reminder.  Those flat grids are constructed from the global grids.  Instead, you want to use the "phi_grid" and "local_theta_grid" attributes of the SimpleSphere class ([see here](https://github.com/rohitsupekar/active_matter_spheres/blob/03f00c309c6a32e32ff9939f352801828498431d/scripts/simple_sphere.py#L25)), which are already multidimensional and should work in parallel.

**Comment by rohitsupekar** [comment]
Thanks! Works in parallel now..
